apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-users-services
  name: service-users
spec:
  ports:
  - name: service-users
    port: 8082
    targetPort: 8080
  selector:
    app: udagram-api-users
